from distutils.core import setup

setup(name='PsyParse',
      version='0.1.0',
      author='Travis Nesland',
      author_email='tnesland@gmail.com',
      packages = [
        'psyparse',
        'psyparse.entry',
        'psyparse.entry.exp_data',
        'psyparse.entry.exp_data.stimuli',
        'psyparse.entry.user_input',
        'psyparse.entry.user_input.keypress',
        'psyparse.handler'
        ],
      package_data = {
        'psyparse':
            ['data/*.txt']
        },
      license='LICENSE.txt',
      description='Code to deal with parsing the default log files generated by PsychoPy.',
      log_description=open('README.txt').read(),
      )
